import { FlowAccount, VideoTask, SystemLog, StudioSettings } from '../types';
import { generateTaskThumbnail } from './videoRenderer';

export const INITIAL_SETTINGS: StudioSettings = {
  concurrency: 4,
  delayBetweenTasksSec: 10,
  outputDirectory: 'D:/HoaiStudioAutomation/Exports/Batch_2026',
  autoRetryCount: 3,
  fileNamingPattern: '{STT}_{Prompt}_{Res}.mp4',
  enableSoundNotification: true,
  enableWatermark: false,
  lowVramMode: false,
  autoRotateAccountOnExhausted: true,
  proxyTimeoutSec: 15,
  // Flow Agent Settings (từ flow.google.com)
  flowServiceUrl: 'https://flow.google.com/',
  confirmationBeforeCreation: 'always',
  defaultImageAspectRatio: '1:1',
  defaultImageModel: 'nano_banana_2_lite',
  defaultVideoAspectRatio: '16:9',
  defaultVideoModel: 'omni_1_1_flash',
};

export const INITIAL_ACCOUNTS: FlowAccount[] = [
  {
    id: 'acc-01',
    email: 'creator.pro.01@gmail.com',
    name: 'Flow Creator Alpha',
    tier: 'ULTRA',
    creditRemaining: 1420,
    creditTotal: 1500,
    proxy: {
      host: '104.28.192.44',
      port: 8080,
      username: 'user_vn_01',
      password: '••••••••',
      type: 'HTTP',
      country: 'VN',
      latencyMs: 38,
      status: 'active',
      lastChecked: 'Vừa xong'
    },
    status: 'in_use',
    enabled: true,
    cookiesSnippet: 'flow_sess_auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.9xK_f...',
    tasksCompleted: 84
  },
  {
    id: 'acc-02',
    email: 'flow.render.studio02@gmail.com',
    name: 'Flow Studio Beta',
    tier: 'ULTRA',
    creditRemaining: 980,
    creditTotal: 1500,
    proxy: {
      host: '143.198.220.12',
      port: 1080,
      username: 'user_sg_02',
      password: '••••••••',
      type: 'SOCKS5',
      country: 'SG',
      latencyMs: 52,
      status: 'active',
      lastChecked: '1 phút trước'
    },
    status: 'in_use',
    enabled: true,
    cookiesSnippet: 'flow_sess_auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.3lM_z...',
    tasksCompleted: 112
  },
  {
    id: 'acc-03',
    email: 'motion.craft.vn03@gmail.com',
    name: 'Motion Craft Gamma',
    tier: 'PRO',
    creditRemaining: 440,
    creditTotal: 500,
    proxy: {
      host: '167.99.78.91',
      port: 8080,
      username: 'user_us_03',
      password: '••••••••',
      type: 'HTTP',
      country: 'US',
      latencyMs: 145,
      status: 'active',
      lastChecked: '3 phút trước'
    },
    status: 'in_use',
    enabled: true,
    cookiesSnippet: 'flow_sess_auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.7vP_q...',
    tasksCompleted: 67
  },
  {
    id: 'acc-04',
    email: 'viral.video.fast04@gmail.com',
    name: 'Viral Video Delta',
    tier: 'PRO',
    creditRemaining: 310,
    creditTotal: 500,
    proxy: {
      host: '198.244.150.23',
      port: 1080,
      username: 'user_jp_04',
      password: '••••••••',
      type: 'SOCKS5',
      country: 'JP',
      latencyMs: 76,
      status: 'active',
      lastChecked: '2 phút trước'
    },
    status: 'in_use',
    enabled: true,
    cookiesSnippet: 'flow_sess_auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.1aC_b...',
    tasksCompleted: 49
  },
  {
    id: 'acc-05',
    email: 'auto.cinematic.05@gmail.com',
    name: 'Auto Cine Epsilon',
    tier: 'PRO',
    creditRemaining: 490,
    creditTotal: 500,
    proxy: {
      host: '185.190.141.65',
      port: 8080,
      username: 'user_de_05',
      password: '••••••••',
      type: 'HTTP',
      country: 'DE',
      latencyMs: 180,
      status: 'active',
      lastChecked: '10 phút trước'
    },
    status: 'active',
    enabled: true,
    cookiesSnippet: 'flow_sess_auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.8kX_w...',
    tasksCompleted: 35
  },
  {
    id: 'acc-06',
    email: 'tiktok.reels.flow06@gmail.com',
    name: 'TikTok Master 06',
    tier: 'PRO',
    creditRemaining: 390,
    creditTotal: 500,
    proxy: {
      host: '103.77.108.20',
      port: 8080,
      username: 'user_vn_06',
      password: '••••••••',
      type: 'HTTP',
      country: 'VN',
      latencyMs: 25,
      status: 'active',
      lastChecked: '5 phút trước'
    },
    status: 'active',
    enabled: true,
    cookiesSnippet: 'flow_sess_auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.4bY_u...',
    tasksCompleted: 78
  },
  {
    id: 'acc-07',
    email: 'short.clips.hq07@gmail.com',
    name: 'Short Clips 07',
    tier: 'FREE',
    creditRemaining: 0,
    creditTotal: 50,
    proxy: {
      host: '104.28.192.88',
      port: 8080,
      username: 'user_vn_07',
      password: '••••••••',
      type: 'HTTP',
      country: 'VN',
      latencyMs: 40,
      status: 'active',
      lastChecked: '12 phút trước'
    },
    status: 'exhausted',
    enabled: true,
    cookiesSnippet: 'flow_sess_auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.2qP_n...',
    tasksCompleted: 25
  },
  {
    id: 'acc-08',
    email: 'youtube.longform08@gmail.com',
    name: 'YT Longform 08',
    tier: 'PRO',
    creditRemaining: 275,
    creditTotal: 500,
    proxy: {
      host: '138.197.140.11',
      port: 1080,
      username: 'user_us_08',
      password: '••••••••',
      type: 'SOCKS5',
      country: 'US',
      latencyMs: 165,
      status: 'active',
      lastChecked: '15 phút trước'
    },
    status: 'active',
    enabled: true,
    cookiesSnippet: 'flow_sess_auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.5mH_t...',
    tasksCompleted: 44
  },
  {
    id: 'acc-09',
    email: 'studio.backup.acc09@gmail.com',
    name: 'Studio Backup 09',
    tier: 'FREE',
    creditRemaining: 35,
    creditTotal: 50,
    proxy: {
      host: '178.62.204.88',
      port: 8080,
      username: 'user_uk_09',
      password: '••••••••',
      type: 'HTTP',
      country: 'UK',
      latencyMs: 195,
      status: 'active',
      lastChecked: '25 phút trước'
    },
    status: 'active',
    enabled: true,
    cookiesSnippet: 'flow_sess_auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.0tL_r...',
    tasksCompleted: 8
  },
  {
    id: 'acc-10',
    email: 'proxy.fail.test10@gmail.com',
    name: 'Proxy Test 10',
    tier: 'PRO',
    creditRemaining: 500,
    creditTotal: 500,
    proxy: {
      host: '192.241.130.5',
      port: 8080,
      username: 'user_us_10',
      password: '••••••••',
      type: 'HTTP',
      country: 'US',
      latencyMs: 999,
      status: 'error',
      lastChecked: '5 phút trước'
    },
    status: 'error',
    enabled: true,
    cookiesSnippet: 'flow_sess_auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.9jK_l...',
    tasksCompleted: 0
  },
  {
    id: 'acc-11',
    email: 'anime.render.flow11@gmail.com',
    name: 'Anime Flow 11',
    tier: 'ULTRA',
    creditRemaining: 1380,
    creditTotal: 1500,
    proxy: {
      host: '103.116.104.5',
      port: 1080,
      username: 'user_jp_11',
      password: '••••••••',
      type: 'SOCKS5',
      country: 'JP',
      latencyMs: 72,
      status: 'active',
      lastChecked: '4 phút trước'
    },
    status: 'active',
    enabled: true,
    cookiesSnippet: 'flow_sess_auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.6wE_y...',
    tasksCompleted: 62
  },
  {
    id: 'acc-12',
    email: 'nature.ambient.12@gmail.com',
    name: 'Nature Studio 12',
    tier: 'PRO',
    creditRemaining: 410,
    creditTotal: 500,
    proxy: {
      host: '14.225.210.99',
      port: 8080,
      username: 'user_vn_12',
      password: '••••••••',
      type: 'HTTP',
      country: 'VN',
      latencyMs: 31,
      status: 'active',
      lastChecked: '6 phút trước'
    },
    status: 'active',
    enabled: true,
    cookiesSnippet: 'flow_sess_auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.7xQ_u...',
    tasksCompleted: 29
  },
  {
    id: 'acc-13',
    email: 'brand.commercial.13@gmail.com',
    name: 'Brand Ads 13',
    tier: 'PRO',
    creditRemaining: 340,
    creditTotal: 500,
    proxy: {
      host: '128.199.180.44',
      port: 1080,
      username: 'user_sg_13',
      password: '••••••••',
      type: 'SOCKS5',
      country: 'SG',
      latencyMs: 48,
      status: 'active',
      lastChecked: '8 phút trước'
    },
    status: 'active',
    enabled: true,
    cookiesSnippet: 'flow_sess_auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.2aP_v...',
    tasksCompleted: 38
  },
  {
    id: 'acc-14',
    email: 'cyberpunk.flow.14@gmail.com',
    name: 'Cyberpunk Lab 14',
    tier: 'PRO',
    creditRemaining: 290,
    creditTotal: 500,
    proxy: {
      host: '159.89.195.20',
      port: 8080,
      username: 'user_us_14',
      password: '••••••••',
      type: 'HTTP',
      country: 'US',
      latencyMs: 155,
      status: 'active',
      lastChecked: '11 phút trước'
    },
    status: 'active',
    enabled: true,
    cookiesSnippet: 'flow_sess_auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.3kL_m...',
    tasksCompleted: 53
  },
  {
    id: 'acc-15',
    email: 'fashion.runway.15@gmail.com',
    name: 'Fashion Auto 15',
    tier: 'ULTRA',
    creditRemaining: 1250,
    creditTotal: 1500,
    proxy: {
      host: '104.28.192.12',
      port: 8080,
      username: 'user_vn_15',
      password: '••••••••',
      type: 'HTTP',
      country: 'VN',
      latencyMs: 34,
      status: 'active',
      lastChecked: '7 phút trước'
    },
    status: 'active',
    enabled: true,
    cookiesSnippet: 'flow_sess_auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.9tC_q...',
    tasksCompleted: 89
  },
  {
    id: 'acc-16',
    email: 'story.narrative.16@gmail.com',
    name: 'Story Maker 16',
    tier: 'PRO',
    creditRemaining: 470,
    creditTotal: 500,
    proxy: {
      host: '165.227.160.8',
      port: 1080,
      username: 'user_sg_16',
      password: '••••••••',
      type: 'SOCKS5',
      country: 'SG',
      latencyMs: 50,
      status: 'active',
      lastChecked: '9 phút trước'
    },
    status: 'active',
    enabled: true,
    cookiesSnippet: 'flow_sess_auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.5bN_k...',
    tasksCompleted: 22
  },
  {
    id: 'acc-17',
    email: 'drone.scenic.17@gmail.com',
    name: 'Scenic Drone 17',
    tier: 'FREE',
    creditRemaining: 20,
    creditTotal: 50,
    proxy: {
      host: '103.77.108.55',
      port: 8080,
      username: 'user_vn_17',
      password: '••••••••',
      type: 'HTTP',
      country: 'VN',
      latencyMs: 29,
      status: 'active',
      lastChecked: '14 phút trước'
    },
    status: 'active',
    enabled: true,
    cookiesSnippet: 'flow_sess_auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.4uM_o...',
    tasksCompleted: 15
  },
  {
    id: 'acc-18',
    email: 'lux.watch.car18@gmail.com',
    name: 'Luxury Product 18',
    tier: 'PRO',
    creditRemaining: 380,
    creditTotal: 500,
    proxy: {
      host: '185.190.141.12',
      port: 8080,
      username: 'user_de_18',
      password: '••••••••',
      type: 'HTTP',
      country: 'DE',
      latencyMs: 172,
      status: 'active',
      lastChecked: '18 phút trước'
    },
    status: 'active',
    enabled: true,
    cookiesSnippet: 'flow_sess_auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.8iP_e...',
    tasksCompleted: 41
  },
  {
    id: 'acc-19',
    email: 'space.sci.fi19@gmail.com',
    name: 'Sci-Fi Cosmos 19',
    tier: 'PRO',
    creditRemaining: 420,
    creditTotal: 500,
    proxy: {
      host: '198.244.150.88',
      port: 1080,
      username: 'user_jp_19',
      password: '••••••••',
      type: 'SOCKS5',
      country: 'JP',
      latencyMs: 79,
      status: 'active',
      lastChecked: '21 phút trước'
    },
    status: 'active',
    enabled: true,
    cookiesSnippet: 'flow_sess_auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.1yR_m...',
    tasksCompleted: 33
  },
  {
    id: 'acc-20',
    email: 'motion.graphics.20@gmail.com',
    name: 'Motion 20 Pro',
    tier: 'ULTRA',
    creditRemaining: 1490,
    creditTotal: 1500,
    proxy: {
      host: '14.225.210.45',
      port: 8080,
      username: 'user_vn_20',
      password: '••••••••',
      type: 'HTTP',
      country: 'VN',
      latencyMs: 27,
      status: 'active',
      lastChecked: '2 phút trước'
    },
    status: 'active',
    enabled: true,
    cookiesSnippet: 'flow_sess_auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.6wA_b...',
    tasksCompleted: 95
  },
  {
    id: 'acc-21',
    email: 'macro.cinematic.21@gmail.com',
    name: 'Macro Cine 21',
    tier: 'PRO',
    creditRemaining: 360,
    creditTotal: 500,
    proxy: {
      host: '143.198.220.88',
      port: 1080,
      username: 'user_sg_21',
      password: '••••••••',
      type: 'SOCKS5',
      country: 'SG',
      latencyMs: 55,
      status: 'active',
      lastChecked: '13 phút trước'
    },
    status: 'active',
    enabled: true,
    cookiesSnippet: 'flow_sess_auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.3kF_r...',
    tasksCompleted: 27
  },
  {
    id: 'acc-22',
    email: 'history.documentary.22@gmail.com',
    name: 'Documentary 22',
    tier: 'FREE',
    creditRemaining: 0,
    creditTotal: 50,
    proxy: {
      host: '167.99.78.22',
      port: 8080,
      username: 'user_us_22',
      password: '••••••••',
      type: 'HTTP',
      country: 'US',
      latencyMs: 150,
      status: 'active',
      lastChecked: '17 phút trước'
    },
    status: 'exhausted',
    enabled: true,
    cookiesSnippet: 'flow_sess_auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.7dL_p...',
    tasksCompleted: 20
  },
  {
    id: 'acc-23',
    email: 'future.cities.23@gmail.com',
    name: 'Future Cities 23',
    tier: 'PRO',
    creditRemaining: 450,
    creditTotal: 500,
    proxy: {
      host: '104.28.192.67',
      port: 8080,
      username: 'user_vn_23',
      password: '••••••••',
      type: 'HTTP',
      country: 'VN',
      latencyMs: 35,
      status: 'active',
      lastChecked: '4 phút trước'
    },
    status: 'active',
    enabled: true,
    cookiesSnippet: 'flow_sess_auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.8fH_n...',
    tasksCompleted: 31
  },
  {
    id: 'acc-24',
    email: 'vfx.particle.master24@gmail.com',
    name: 'VFX Master 24',
    tier: 'PRO',
    creditRemaining: 500,
    creditTotal: 500,
    proxy: {
      host: '178.62.204.15',
      port: 8080,
      username: 'user_uk_24',
      password: '••••••••',
      type: 'HTTP',
      country: 'UK',
      latencyMs: 188,
      status: 'active',
      lastChecked: '20 phút trước'
    },
    status: 'active',
    enabled: true,
    cookiesSnippet: 'flow_sess_auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.2gK_v...',
    tasksCompleted: 14
  }
];

export const INITIAL_TASKS: VideoTask[] = [
  {
    id: 'task-101',
    indexNumber: 1,
    prompt: 'Cinematic drone shot of Ha Long Bay limestone karsts at sunrise, golden sunrays through emerald water, ultra-realistic 4k',
    model: 'veo_3_1_quality',
    aspectRatio: '16:9',
    resolution: '1080p',
    duration: 6,
    variations: 1,
    status: 'completed',
    progress: 100,
    activeWorkerId: null,
    assignedAccountId: 'acc-01',
    assignedAccountEmail: 'creator.pro.01@gmail.com',
    thumbnailUrl: generateTaskThumbnail('Cinematic drone shot of Ha Long Bay limestone karsts at sunrise', '16:9'),
    downloadSpeed: '24.5 MB/s',
    retryCount: 0,
    maxRetries: 3,
    createdAt: '2026-09-28 19:15:20',
    completedAt: '2026-09-28 19:16:10',
    outputFilePath: 'D:/HoaiStudioAutomation/Exports/01_HaLongBay_Sunrise_1080p.mp4',
    fileSizeBytes: 28450120
  },
  {
    id: 'task-102',
    indexNumber: 2,
    prompt: 'Cyberpunk street food stall in futuristic Saigon, neon reflections in rainwater puddles, flying hover vehicles, steam rising',
    model: 'omni_1_1_flash',
    aspectRatio: '9:16',
    resolution: '1080p',
    duration: 6,
    variations: 1,
    status: 'completed',
    progress: 100,
    activeWorkerId: null,
    assignedAccountId: 'acc-02',
    assignedAccountEmail: 'flow.render.studio02@gmail.com',
    thumbnailUrl: generateTaskThumbnail('Cyberpunk street food stall in futuristic Saigon, neon reflections', '9:16'),
    downloadSpeed: '32.1 MB/s',
    retryCount: 0,
    maxRetries: 3,
    createdAt: '2026-09-28 19:16:15',
    completedAt: '2026-09-28 19:17:02',
    outputFilePath: 'D:/HoaiStudioAutomation/Exports/02_CyberpunkSaigon_Neon_1080p.mp4',
    fileSizeBytes: 31200400
  },
  {
    id: 'task-103',
    indexNumber: 3,
    prompt: 'Macro commercial shot of a luxury swiss chronograph watch mechanism, gold gears turning smoothly, high-speed camera slow motion',
    model: 'veo_3_1_quality',
    aspectRatio: '16:9',
    resolution: '4k',
    duration: 8,
    variations: 1,
    status: 'completed',
    progress: 100,
    activeWorkerId: null,
    assignedAccountId: 'acc-03',
    assignedAccountEmail: 'motion.craft.vn03@gmail.com',
    thumbnailUrl: generateTaskThumbnail('Macro commercial shot of luxury swiss chronograph watch mechanism gold', '16:9'),
    downloadSpeed: '28.4 MB/s',
    retryCount: 0,
    maxRetries: 3,
    createdAt: '2026-09-28 19:17:10',
    completedAt: '2026-09-28 19:18:25',
    outputFilePath: 'D:/HoaiStudioAutomation/Exports/03_SwissWatch_Macro_4k.mp4',
    fileSizeBytes: 64200800
  },
  // Active Thread 1
  {
    id: 'task-104',
    indexNumber: 4,
    prompt: 'Space exploration spacecraft gliding past Saturn planetary rings, cosmic dust illumination, hyper-realistic astrophysic simulation',
    model: 'veo_3_1_fast',
    aspectRatio: '16:9',
    resolution: '1080p',
    duration: 6,
    variations: 1,
    status: 'processing',
    progress: 68,
    stageMessage: 'Đang tạo (Luồng 1) - Diffusion Frame 38/60',
    activeWorkerId: 1,
    assignedAccountId: 'acc-01',
    assignedAccountEmail: 'creator.pro.01@gmail.com',
    thumbnailUrl: generateTaskThumbnail('Space exploration spacecraft gliding past Saturn planetary rings', '16:9'),
    downloadSpeed: '18.9 MB/s',
    retryCount: 0,
    maxRetries: 3,
    createdAt: '2026-09-28 19:20:00'
  },
  // Active Thread 2
  {
    id: 'task-105',
    indexNumber: 5,
    prompt: 'Fashion model walking down a futuristic minimalist Paris runway, iridescent fabric fluttering in slow motion, studio spotlight',
    model: 'omni_1_1_flash',
    aspectRatio: '9:16',
    resolution: '1080p',
    duration: 6,
    variations: 1,
    status: 'processing',
    progress: 52,
    stageMessage: 'Đang tạo (Luồng 2) - Latent Denoising 52%',
    activeWorkerId: 2,
    assignedAccountId: 'acc-02',
    assignedAccountEmail: 'flow.render.studio02@gmail.com',
    thumbnailUrl: generateTaskThumbnail('Fashion model walking down a futuristic minimalist Paris runway', '9:16'),
    downloadSpeed: '22.0 MB/s',
    retryCount: 0,
    maxRetries: 3,
    createdAt: '2026-09-28 19:20:05'
  },
  // Active Thread 3
  {
    id: 'task-106',
    indexNumber: 6,
    prompt: 'Anime samurai duel in a bamboo forest during cherry blossom storm, sword blade reflection, dynamic camera pan, Studio Ghibli style',
    model: 'veo_3_1_lite',
    aspectRatio: '16:9',
    resolution: '1080p',
    duration: 6,
    variations: 1,
    status: 'processing',
    progress: 84,
    stageMessage: 'Đang tải video về máy (Luồng 3) - 84%',
    activeWorkerId: 3,
    assignedAccountId: 'acc-03',
    assignedAccountEmail: 'motion.craft.vn03@gmail.com',
    thumbnailUrl: generateTaskThumbnail('Anime samurai duel in bamboo forest cherry blossom anime girl warrior', '16:9'),
    downloadSpeed: '35.4 MB/s',
    retryCount: 0,
    maxRetries: 3,
    createdAt: '2026-09-28 19:20:10'
  },
  // Active Thread 4
  {
    id: 'task-107',
    indexNumber: 7,
    prompt: 'Hypercar racing through coastal highway in Monaco at twilight, motion blur wheels, atmospheric exhaust flame, 8k cinematic shot',
    model: 'veo_3_1_quality',
    aspectRatio: '16:9',
    resolution: '1080p',
    duration: 8,
    variations: 1,
    status: 'processing',
    progress: 29,
    stageMessage: 'Đang tạo (Luồng 4) - Sampling Steps 15/50',
    activeWorkerId: 4,
    assignedAccountId: 'acc-04',
    assignedAccountEmail: 'viral.video.fast04@gmail.com',
    thumbnailUrl: generateTaskThumbnail('Hypercar racing through coastal highway luxury car commercial', '16:9'),
    downloadSpeed: '15.2 MB/s',
    retryCount: 0,
    maxRetries: 3,
    createdAt: '2026-09-28 19:20:15'
  },
  // Queued Tasks
  {
    id: 'task-108',
    indexNumber: 8,
    prompt: 'Mystical ancient temple deep inside Amazon rainforest waterfall, glowing mystical runes, lush green foliage and exotic birds flying',
    model: 'veo_3_1_quality',
    aspectRatio: '9:16',
    resolution: '1080p',
    duration: 6,
    variations: 1,
    status: 'queued',
    progress: 0,
    stageMessage: 'Đang trong hàng đợi (Vị trí 1)',
    retryCount: 0,
    maxRetries: 3,
    createdAt: '2026-09-28 19:21:00'
  },
  {
    id: 'task-109',
    indexNumber: 9,
    prompt: 'Coffee latte art creation from top-down macro angle, pouring creamy milk into dark espresso creating symmetrical swan pattern',
    model: 'veo_3_1_lite',
    aspectRatio: '1:1',
    resolution: '1080p',
    duration: 4,
    variations: 1,
    status: 'queued',
    progress: 0,
    stageMessage: 'Đang trong hàng đợi (Vị trí 2)',
    retryCount: 0,
    maxRetries: 3,
    createdAt: '2026-09-28 19:21:05'
  },
  {
    id: 'task-110',
    indexNumber: 10,
    prompt: 'Futuristic laboratory with robotic arms assembling microscopic quantum processors, blue laser precision beams, 4k tech showcase',
    model: 'veo_3_1_fast',
    aspectRatio: '16:9',
    resolution: '1080p',
    duration: 6,
    variations: 1,
    status: 'queued',
    progress: 0,
    stageMessage: 'Đang trong hàng đợi (Vị trí 3)',
    retryCount: 0,
    maxRetries: 3,
    createdAt: '2026-09-28 19:21:10'
  }
];

export const INITIAL_LOGS: SystemLog[] = [
  {
    id: 'log-01',
    timestamp: '19:15:02',
    level: 'INFO',
    message: 'Khởi động phần mềm Hoai Studio Automation v2.4 (Parallel Engine 4 Threads).',
    meta: { version: '2.4.0', os: 'Desktop App' }
  },
  {
    id: 'log-02',
    timestamp: '19:15:04',
    level: 'INFO',
    message: 'Kiểm tra 24 tài khoản trong cơ sở dữ liệu: 20 tài khoản khả dụng, 2 tài khoản hết credit, 1 lỗi proxy, 1 đang chờ.',
  },
  {
    id: 'log-03',
    timestamp: '19:15:07',
    level: 'SUCCESS',
    message: 'Kiểm tra kết nối Proxy: 22 Proxy hoạt động bình thường, độ trễ trung bình 48ms.',
  },
  {
    id: 'log-04',
    timestamp: '19:15:20',
    level: 'WORKER',
    message: '[Luồng 1] Gán tài khoản creator.pro.01@gmail.com (ULTRA - Credit: 1420) cho Task #1',
    accountEmail: 'creator.pro.01@gmail.com',
    taskId: 'task-101'
  },
  {
    id: 'log-05',
    timestamp: '19:16:10',
    level: 'SUCCESS',
    message: '[Luồng 1] Hoàn thành render Task #1 Ha Long Bay. Lưu tệp: D:/FlowVideoStudio/Exports/01_HaLongBay_Sunrise_1080p.mp4 (27.1 MB)',
    taskId: 'task-101'
  },
  {
    id: 'log-06',
    timestamp: '19:17:02',
    level: 'SUCCESS',
    message: '[Luồng 2] Hoàn thành render Task #2 Cyberpunk Saigon. Đã tải về máy thành công qua Proxy SG-143.198 (32.1 MB/s)',
    taskId: 'task-102'
  },
  {
    id: 'log-07',
    timestamp: '19:18:25',
    level: 'SUCCESS',
    message: '[Luồng 3] Hoàn thành render Task #3 Swiss Watch Macro 4K. Trừ 20 credit trên tài khoản motion.craft.vn03@gmail.com (Còn 440)',
    taskId: 'task-103'
  },
  {
    id: 'log-08',
    timestamp: '19:20:00',
    level: 'WORKER',
    message: '[Multi-threading] Đã kích hoạt 4 Worker song song (Luồng 1: Task #4, Luồng 2: Task #5, Luồng 3: Task #6, Luồng 4: Task #7)',
  },
  {
    id: 'log-09',
    timestamp: '19:20:12',
    level: 'INFO',
    message: '[API Request] Gửi prompt Task #4 lên Flow Inference Endpoint (Model: Flow Pro v3.1, Latent: 1080p 6s)',
  }
];

export const SAMPLE_PROMPT_PRESETS = [
  {
    title: 'Cinematic Phong Cảnh & Drone (4K)',
    prompts: [
      'Cinematic aerial drone shot of golden terraced rice fields in Mu Cang Chai at sunrise, morning mist rolling over mountains, 8k ultra realistic',
      'Dramatic low angle shot of ancient Japanese pagoda surrounded by autumn red maple leaves, gentle falling rain, cinematic lighting, 4k',
      'Slow drone flyover above crystal clear turquoise waves crashing against black volcanic rocks in Iceland, dramatic cloudy sky, 60fps cinematic',
      'Spectacular northern lights aurora borealis glowing vibrant green over snowy pine forest and wooden cabin in Norway, hyper-realistic'
    ]
  },
  {
    title: 'Cyberpunk & Sci-Fi Tương Lai',
    prompts: [
      'Cyberpunk street food stall in futuristic neon Tokyo, heavy rain reflecting holographic ads, noodle chef with cybernetic arm, steam rising',
      'Futuristic vertical megalopolis at midnight, flying speeder cars traveling along light highways, giant holographic koi fish floating in sky',
      'Giant humanoid battle mech walking through ruined alien desert planet, sandstorm winds, cracked armor with blue glowing energy core',
      'Interior view of deep space station observation dome, astronaut floating looking down at rotating neon planet below, cinematic sci-fi'
    ]
  },
  {
    title: 'Quảng Cáo Sản Phẩm Cao Cấp (Commercial)',
    prompts: [
      'Macro luxury commercial shot of premium perfume bottle emerging from crystalline water, gentle water ripples, elegant studio backlight',
      'Extreme close-up of luxury sport chronograph watch mechanism, golden tourbillon spinning with micro-gears, cinematic slow motion 4k',
      'High-end electric hypercar rotating on black reflective marble turntable, dramatic rim lighting tracing sleek aerodynamic curves',
      'Pouring rich creamy milk into cold brew iced coffee glass in slow motion, ice cubes clinking, condensation droplets on glass'
    ]
  },
  {
    title: 'TikTok & Short Video Viral Trend',
    prompts: [
      'Cute fluffy baby panda eating bamboo shoot in sunlit bamboo garden, expressive big eyes, ultra adorable, 9:16 vertical video',
      'Time-lapse of bustling street food market in Bangkok at dusk, vibrant colorful lights, sizzling street woks, cinematic fast-paced motion',
      'Dynamic breakdancer performing power moves in urban underground subway tunnel, neon graffiti art, dramatic spotlight',
      'Satisfying kinetic sand cutting and slicing with glowing laser knife, ASMR visual satisfaction, vibrant multi-color layers'
    ]
  }
];
